#!/bin/bash
# n8n-core 개발 환경에서 커스텀 노드 로드를 위한 패치 스크립트
# 사용법: ./patch-n8n-dev.sh [n8n-core-path]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MONOREPO_ROOT="$(dirname "$SCRIPT_DIR")"
PACKAGES_DIR="$MONOREPO_ROOT/packages"

# n8n-core 경로 (기본값 또는 인자로 받음)
N8N_CORE_PATH="${1:-/Users/junwoobang/n8n/n8n-core}"
N8N_CLI_PATH="$N8N_CORE_PATH/packages/cli"
ENV_FILE="$N8N_CLI_PATH/.env"

# 색상 정의
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== n8n Custom Nodes Patch Tool ===${NC}"
echo ""

# n8n-core 경로 확인
if [ ! -d "$N8N_CLI_PATH" ]; then
    echo -e "${RED}Error: n8n CLI path not found: $N8N_CLI_PATH${NC}"
    echo "Usage: $0 [n8n-core-path]"
    exit 1
fi

# 빌드된 패키지 경로 수집
EXTENSIONS=""
PACKAGE_COUNT=0

echo -e "${YELLOW}Scanning packages...${NC}"
for pkg_dir in "$PACKAGES_DIR"/*/; do
    pkg_name=$(basename "$pkg_dir")

    if [ -d "$pkg_dir/dist" ]; then
        # 절대 경로 사용
        pkg_path=$(cd "$pkg_dir" && pwd)

        if [ -n "$EXTENSIONS" ]; then
            EXTENSIONS="$EXTENSIONS;$pkg_path"
        else
            EXTENSIONS="$pkg_path"
        fi

        echo -e "  ${GREEN}✓${NC} $pkg_name"
        ((PACKAGE_COUNT++))
    else
        echo -e "  ${YELLOW}⚠${NC} $pkg_name (not built, run 'pnpm build')"
    fi
done

if [ $PACKAGE_COUNT -eq 0 ]; then
    echo -e "${RED}Error: No built packages found.${NC}"
    echo "Run 'pnpm build' in the monorepo root first."
    exit 1
fi

echo ""
echo -e "${GREEN}Found $PACKAGE_COUNT package(s)${NC}"
echo ""

# .env 파일 패치
ENV_VAR="N8N_CUSTOM_EXTENSIONS=\"$EXTENSIONS\""

if [ -f "$ENV_FILE" ]; then
    # 기존 .env 파일이 있으면 N8N_CUSTOM_EXTENSIONS 라인 업데이트/추가
    if grep -q "^N8N_CUSTOM_EXTENSIONS=" "$ENV_FILE"; then
        # 기존 라인 교체
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s|^N8N_CUSTOM_EXTENSIONS=.*|$ENV_VAR|" "$ENV_FILE"
        else
            sed -i "s|^N8N_CUSTOM_EXTENSIONS=.*|$ENV_VAR|" "$ENV_FILE"
        fi
        echo -e "${GREEN}Updated${NC} N8N_CUSTOM_EXTENSIONS in $ENV_FILE"
    else
        # 새 라인 추가
        echo "" >> "$ENV_FILE"
        echo "$ENV_VAR" >> "$ENV_FILE"
        echo -e "${GREEN}Added${NC} N8N_CUSTOM_EXTENSIONS to $ENV_FILE"
    fi
else
    # 새 .env 파일 생성
    echo "# n8n Custom Extensions" > "$ENV_FILE"
    echo "# Auto-generated by patch-n8n-dev.sh" >> "$ENV_FILE"
    echo "" >> "$ENV_FILE"
    echo "$ENV_VAR" >> "$ENV_FILE"
    echo -e "${GREEN}Created${NC} $ENV_FILE"
fi

echo ""
echo -e "${GREEN}=== Patch Complete ===${NC}"
echo ""
echo "Restart n8n to load custom nodes."
echo ""
echo -e "${YELLOW}Current N8N_CUSTOM_EXTENSIONS:${NC}"
echo "$EXTENSIONS" | tr ';' '\n' | while read -r path; do
    echo "  - $path"
done
